"""empty message

Revision ID: 065a3f25b60c
Revises: 
Create Date: 2021-10-13 20:28:01.654932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065a3f25b60c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=True), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('humid', sa.Float(), nullable=True),
    sa.Column('heat', sa.Float(), nullable=True),
    sa.Column('dust', sa.Float(), nullable=True),
    sa.Column('co2', sa.Integer(), nullable=True),
    sa.Column('tvoc', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_timestamp'), 'data', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=True), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_data_timestamp'), table_name='data')
    op.drop_table('data')
    # ### end Alembic commands ###
