"""empty message

Revision ID: bbcea95fd7c2
Revises: 065a3f25b60c
Create Date: 2021-10-19 12:41:00.037251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbcea95fd7c2'
down_revision = '065a3f25b60c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=True), nullable=False),
    sa.Column('serial_num', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('data', sa.Column('device_id', sa.Integer(), nullable=True))
    op.alter_column('data', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, cycle=True),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('ix_data_timestamp', table_name='data')
    op.create_foreign_key(None, 'data', 'device', ['device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.create_index('ix_data_timestamp', 'data', ['timestamp'], unique=False)
    op.alter_column('data', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('data', 'device_id')
    op.drop_table('device')
    # ### end Alembic commands ###
