"""Data table

Revision ID: eb1ee2ba619b
Revises: 90e64a231dd8
Create Date: 2021-10-11 14:10:38.668249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1ee2ba619b'
down_revision = '90e64a231dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('humid', sa.Float(), nullable=True),
    sa.Column('heat', sa.Float(), nullable=True),
    sa.Column('dust', sa.Float(), nullable=True),
    sa.Column('co2', sa.Integer(), nullable=True),
    sa.Column('tvoc', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_timestamp'), 'data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_timestamp'), table_name='data')
    op.drop_table('data')
    # ### end Alembic commands ###
